services:
  - type: web
    name: node-express-app
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    region: oregon
    healthCheckPath: /

databases:
  - type: sqlite
    name: sqlite-database
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sqlite-database
          property: connectionString
